- name: Make sure EPEL repo is available
  copy: src=etc_yum.repos.d_epel.repo dest=/etc/yum.repos.d/epel.repo
  tags:
    - host_setup_livecd

- name: Verify existence of RPM-GPG-KEY-EPEL-7
  copy: src=etc_pki_rpm-gpg_RPM-GPG-KEY-EPEL-7 dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
  tags:
    - host_setup_livecd
